# https://dev.azure.com/open-peer-power

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - base/requirements.txt
pr: none
variables:
  - name: versionWheels
    value: '1.12.4-3.8-alpine3.12'
resources:
  repositories:
    - repository: azure
      type: github
      name: 'openpeerpower/ci-azure'
      endpoint: 'openpeerpower'

jobs:
- template: templates/azp-job-wheels.yaml@azure
  parameters:
    builderVersion: '$(versionWheels)'
    builderApk: 'build-base;mariadb-dev;postgresql-dev;unixodbc-dev;libffi-dev;cmake;ncurses;git'
    wheelsRequirement: 'base/requirements.txt'
